### ISSUE TITLE
Question about porting PHP backend to node.js

### ISSUE THREAD

**Issue by metalaureate** [cropzoom/cropzoom#10]
I thought I'd take a crack at porting your PHP imagemagick scripts to node.js

There are two PHP files included in your demo. Which one should I be using? Your demo POSTS to resize_and_crop.php, which makes use of functions that aren't defined such as imagecreatetruecolor, but there is also resize_and_crop_imagick.php

I use this https://github.com/rsms/node-imagemagick as my node wrapper for imagemagick.

**Comment by gastonrobledo-santex** [comment]
Both could be used the main difference between them is that one use GD and the other use IMagic library. that's all.

**Comment by metalaureate** [comment]
Thanks for the clarification.
