### ISSUE TITLE
API for setting image location, rotation, and zoom

### ISSUE THREAD

**Issue by wulftone** [cropzoom/cropzoom#2]
This is more of a feature request....
Cropzoom currently has a nice api for setting up the selector using the `setSelector` function, but I would like to see an API that developers could use to programatically set the image's location, rotation, and zoom, like a `setImage` function.

I save my user's image modifications in my database so that the next time they open up the image editor, it automatically sets up the image's `x`, `y`, `r`, and `z` where they last saved it.  This allows them to make adjustments to their crops and whatnot more easily.

Currently, I've got a hacky way of doing this, but if I just had an API in cropzoom to do this, it'd be a breeze.

Any chance this could make it in?

**Comment by wulftone** [comment]
Here's some code that does what I want... I know it duplicates some stuff internally, but it does the job:

``` coffeescript
  $.fn.extend

    ###
    Function to set the image position and zoom.

    Internally, `imageData` sets the values that get passed back and
    forth between the relevant calculations.  Displaying changes is done
    entirely by modifying the css of the image.

    @param x [Number] X-coordinate for top-left of crop area
    @param y [Number] Y-coordinate for top-left of crop area
    @param z [Number] Zoom amount
    @param r [Number] Rotation angle
    ###
    setImage: (x, y, z, r) ->
      _self = $(this)
      imageData = _self.data 'image'
      $image = _self.find "img[src='#{imageData.source}']"


      # Position
      imageData.posX = x
      imageData.posY = y


      # Zoom
      width = $image[0].naturalWidth
      height = $image[0].naturalHeight

      w = z * width
      h = z * height

      imageData.w = w
      imageData.h = h
      imageData.scaleX = (width / w)
      imageData.scaleY = (height / h)


      # Rotation
      imageData.rotation = r
      angle = imageData.rotation * Math.PI / 180
      sin = Math.sin(angle)
      cos = Math.cos(angle)

      # (0,0) stays as (0, 0)

      # (w,0) rotation
      x1 = cos * imageData.w
      y1 = sin * imageData.w

      # (0,h) rotation
      x2 = -sin * imageData.h
      y2 = cos * imageData.h

      # (w,h) rotation
      x3 = cos * imageData.w - sin * imageData.h
      y3 = sin * imageData.w + cos * imageData.h
      minX = Math.min(0, x1, x2, x3)
      maxX = Math.max(0, x1, x2, x3)
      minY = Math.min(0, y1, y2, y3)
      maxY = Math.max(0, y1, y2, y3)

      imageData.rotW = maxX - minX
      imageData.rotH = maxY - minY
      imageData.rotY = minY
      imageData.rotX = minX

      rotation = "rotate(" + imageData.rotation + "deg)"

      # Apply changes to CSS so the user can see them.
      $image.css
        transform: rotation
        "-webkit-transform": rotation
        "-ms-transform": rotation
        msTransform: rotation
        top: imageData.posY
        left: imageData.posX
        width: w + "px"
        height: h + "px"
```

I put it right next to the `setSelector` code so it's available from the `cropzoom` instance.

**Comment by gastonrobledo** [comment]
Hi Trevor

I'm not sure but you can set some properties at beginning to do this.
These properties are x, y, startZoom and rotation.

Thanks

**Comment by wulftone** [comment]
Yeah, I saw that, however, I needed to manipulate the image _after_ it was loaded into cropzoom.  Regardless, I forked the project and was able to build what I need, so thank you for providing a library I could fork!

**Comment by gastonrobledo** [comment]
Cool! glad to help!

Thanks!

2013/6/4 Trevor Bortins notifications@github.com

> Yeah, I saw that, however, I needed to manipulate the image _after_ it
> was loaded into cropzoom. Regardless, I forked the project and was able to
> build what I need, so thank you for providing a library I could fork!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cropzoom/cropzoom/issues/2#issuecomment-18931101
> .

## 

_Robledo, Gaston_
_http://about.me/gastonrobledo
*MCE 5 Platinum, C# Senior Developer,
PHP Senior Developer.
JavaScript/jQuery Senior Developer.
*CUIT_: _20-29713599-7_.
_Tel_: _+54 351 153724958_.

**Comment by thawkins** [comment]
Is this going to be added? I need this as well  so that i can support ajax uploads on the same page. We are building a page where a user can upload, crop and rotate an image for use as an avatar. 
The workaround cited above will work, but it means hacking the files each time an update is done.

**Comment by wulftone** [comment]
@thawkins You can see if my fork of the project works for you.  I converted it all to coffeescript and added the above functionality.  I'll keep it up there forever, too.

**Comment by thawkins** [comment]
@wulftone 
where can I get a copy of your fork? 

the insert in the comment above is incomplete, the end of the function is missing.

**Comment by wulftone** [comment]
Either click on my name and look in my repos, or click on the little number next to the fork button for this repo (that will show you all the forks for this repo).

The insert is actually complete.  If you're not familiar with coffeescript, it may look weird.

**Comment by thawkins** [comment]
I just realised that what i really need is something that changes the imsge source after the component has loaded, so i created a hacked version of .restore()  called .restoreTo(url) which patches the $options.image.source before calling restore() 

I have also noticed that if you have the option to enable the selector overlay at start, and you call setSelector after the control has initialised, the overlay is not recalculated and repainted to match the new selector position.

**Comment by wulftone** [comment]
If that's an issue with the original cropzoom, it'd probably be good to open a new issue here for that..  If it's only on mine, please open an issue on my fork (so we can stop spamming this version's issues tracker!)
