### ISSUE TITLE
Version for IE 7 / IE 8 / IE9

### ISSUE THREAD

**Issue by joergi77** [cropzoom/cropzoom#3]
HI,
due to our customer, I must still support IE7, IE8 , IE9 .... and the next generation

I saw that the old version was supporting IE6 + IE7 + IE8

Is there a Version, which is working with all the old browsers? It's not  a problem to make 2 Versions for the customers, but it should work for all browsers!

(i always have a problem with this line: 
 style.addRule('v\:*',"behavior: url(#default#VML);display:inline-block;antiAlias: false");

and yes i allready added the namespace and everything...)

thanks for your help

**Comment by gastonrobledo** [comment]
Yes you have the one in google code. I'll add this code to a separate
branch on github asap.

You can add that behavior directly to the page where you sill use cropzoom.

Thanks

**Comment by joergi77** [comment]
hi @gastonrobledo - I used now this version: https://github.com/cropzoom/cropzoom/commit/674b1397790e53becf2836650eb92746c09ebbda#demo  - with this everything (as fas as i can see now) is working in IE7 + IE8 + IE9 as expected.... perfect
